Реализована основная часть
mikhaylenko-sd/java-explore-with-me pull request #4
Opened 2023-05-26 00:54 UTC by mikhaylenko-sd

2023-05-26 20:29 UTC, Fleaman777 requested changes

2023-05-26 20:29 UTC, Fleaman777 commented on explore-main/src/main/java/ru/practicum/explore/main/event/model/Event.java
> +    private boolean available;
конечно дело вкуса, 
но по мне, если название колонки полностью совпадает с названием поля, то лучше не ставить аннотацию, тем самым не будем загружать код повторяющейся информацией

2023-05-26 20:29 UTC, Fleaman777 commented on explore-main/src/main/java/ru/practicum/explore/main/exceptions/ErrorHandler.java
> +        log.error("Во время работы программы произошла ошибка {}", exception.getMessage());
Во время работы программы произошла ошибк - можно было бы вынести в константу

2023-05-26 20:29 UTC, Fleaman777 commented on explore-main/src/main/java/ru/practicum/explore/main/request/service/RequestService.java
> +                        "Запрашиваемый объект не найден или не доступен", LocalDateTime.now()));
создание эксепшена и просечивания текстовки одинаковое во многих местам, можно вынести в общий метод или константу

2023-05-26 20:29 UTC, Fleaman777 commented on explore-main/src/main/java/ru/practicum/explore/main/user/service/UserService.java
> +                .anyMatch(u -> u.getEmail().equals(user.getEmail()))) {
лучше вынести этот стрим из условия хотя бы в локальную переменную с подходящим названием, что бы улучшить восприятие

2023-05-27 13:08 UTC, mikhaylenko-sd commented on docker-compose.yml
>        - POSTGRES_DB=statServiceDb
это же переменная для образа postgres, зачем ее в application.properties тянуть?

2023-05-27 13:09 UTC, mikhaylenko-sd commented on explore-main/src/main/java/ru/practicum/explore/main/category/controller/CategoryAdminController.java
> +    public CategoryAdminController(CategoryService categoryService) {
мне кажется, прописанный конструктор в случае компонентов спринга лучше, чем аннотация для конструктора, так как идея подсвечивает бины, которые будут внедрены

2023-05-28 17:03 UTC, Fleaman777 requested changes

2023-05-28 17:03 UTC, Fleaman777 commented on explore-main/src/main/java/ru/practicum/explore/main/event/service/EventService.java
> +            pageable = PageRequest.of(from / size, size, Sort.by(Sort.Direction.ASC, "views"));
это if можно было бы немного трасформировать, используя тернарный оператор определить "eventDate" или "views", 
а так же вынести общую часть объекта pageable PageRequest.of(from / size, size, Sort.by(Sort.Direction.ASC

2023-05-28 18:14 UTC, mikhaylenko-sd commented on explore-main/src/main/java/ru/practicum/explore/main/event/service/EventService.java
> +            pageable = PageRequest.of(from / size, size, Sort.by(Sort.Direction.ASC, "views"));
да, согласна, я делаю уже фичу по рейтингам(лайки/дизлайки) и там будет сортировка по рейтингу, так что if понадобится
по второму замечанию: я это уже сделала в фиче и залью вместе с ней

2023-05-29 16:40 UTC, Fleaman777 approved these changes

2023-05-29 21:34 UTC, merged